fm_elfinder:
    assets_path: /assets
    instances:
        default:
            locale: fr
            editor: ckeditor
            fullscreen: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: /public/uploads/images/articles/ckeditor
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg'] # Fichiers autoris√©s
                        upload_deny: ['all']
